from fpdf import FPDF
from datetime import datetime
import io


def export_as_text(question: str, answer: str, sources: list) -> str:
    """
    Export Q&A as plain text string.
    Ready for download as .txt file.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    
    lines = [
        "=" * 60,
        "AI RESEARCH PAPER Q&A — EXPORT",
        f"Generated: {timestamp}",
        "=" * 60,
        "",
        "QUESTION:",
        question,
        "",
        "ANSWER:",
        answer,
        "",
        "=" * 60,
        "SOURCES USED:",
        "=" * 60,
    ]
    
    for i, source in enumerate(sources, 1):
        title = source.get("title", "Unknown")
        authors = source.get("authors", "Unknown")
        arxiv_id = source.get("arxiv_id", "")
        score = source.get("similarity_score", "N/A")
        
        lines.append(f"\nSource {i}: {title}")
        lines.append(f"Authors: {authors}")
        if arxiv_id:
            lines.append(f"ArXiv: https://arxiv.org/abs/{arxiv_id}")
        lines.append(f"Relevance Score: {score}")
    
    lines.append("\n" + "=" * 60)
    lines.append("Generated by AI Research Paper Q&A System")
    
    return "\n".join(lines)


def export_as_pdf(question: str, answer: str, sources: list) -> bytes:
    """
    Export Q&A as PDF bytes.
    Ready for download as .pdf file.
    """
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Title
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 12, "AI Research Paper Q&A", ln=True, align="C")
    
    # Timestamp
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(120, 120, 120)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    pdf.cell(0, 8, f"Generated: {timestamp}", ln=True, align="C")
    pdf.ln(4)
    
    # Divider
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)
    
    # Question section
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(220, 50, 50)
    pdf.cell(0, 8, "QUESTION", ln=True)
    
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(30, 30, 30)
    
    # Clean question text
    clean_question = question.encode(
        "latin-1", errors="replace"
    ).decode("latin-1")
    pdf.multi_cell(0, 7, clean_question)
    pdf.ln(4)
    
    # Answer section
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(30, 100, 200)
    pdf.cell(0, 8, "ANSWER", ln=True)
    
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(30, 30, 30)
    
    # Clean answer text (remove markdown symbols)
    clean_answer = answer.replace("**", "").replace("*", "").replace("#", "")
    clean_answer = clean_answer.encode(
        "latin-1", errors="replace"
    ).decode("latin-1")
    pdf.multi_cell(0, 6, clean_answer)
    pdf.ln(6)
    
    # Sources section
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(50, 150, 50)
    pdf.cell(0, 8, "SOURCES USED", ln=True)
    
    for i, source in enumerate(sources, 1):
        title = source.get("title", "Unknown")
        authors = source.get("authors", "Unknown Authors")
        arxiv_id = source.get("arxiv_id", "")
        score = source.get("similarity_score", "N/A")
        
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(30, 30, 30)
        
        clean_title = f"Source {i}: {title}".encode(
            "latin-1", errors="replace"
        ).decode("latin-1")
        pdf.cell(0, 7, clean_title, ln=True)
        
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(80, 80, 80)
        
        clean_authors = f"Authors: {authors}".encode(
            "latin-1", errors="replace"
        ).decode("latin-1")
        pdf.cell(0, 6, clean_authors, ln=True)
        pdf.cell(0, 6, f"Relevance Score: {score}", ln=True)
        
        if arxiv_id:
            pdf.set_text_color(30, 100, 200)
            pdf.cell(
                0, 6,
                f"ArXiv: https://arxiv.org/abs/{arxiv_id}",
                ln=True
            )
        
        pdf.set_text_color(80, 80, 80)
        pdf.ln(3)
    
    # Footer
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(
        0, 6,
        "Generated by AI Research Paper Q&A System",
        ln=True,
        align="C"
    )
    
    # Return as bytes
    return bytes(pdf.output())